name: Github Actions Publish

on:
  push

jobs:
  release:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      - uses: lukka/get-cmake@latest

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash

      - name: Prepare
        run: |
          python -m pip install --upgrade pip
          pip install conan==1.59.0

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          cmake --build . --config Release

      - name: Install
        run: |
          cd build
          cmake --install . --config Release

      - name: Extract Release Notes
        id: extract_release_notes
        uses: ffurrer2/extract-release-notes@v1

      - name: Zip Release
        run: |
          cd publish
          tar -a -c -f ../playlunky_${{ steps.get_version.outputs.VERSION }}.zip *

      - uses: EndBug/add-and-commit@v9
        with:
          message: 'add build result'
          new_branch: build-result
